### PR TITLE
chore(prettier): Run prettier over project

### PR DESCRIPTION
**Pull request by damassi**
Noticed that we didn't have proper code formatting set up. This does that.

### CODE REVIEW

**Comment by pvinis** [comment]
thanks🙌. I always wrote code with eigens prettier.

**Comment by pvinis** [comment]
it only uses spaces instead of the correct tabs, but ok 😛

**Comment by damassi** [comment]
yah we don't use `tabs` anywhere in any artsy codebase. Its all 2 spaces.

**Comment by pvinis** [comment]
yep yep. exactly. that why I'm not complaining 👍. convention over ..perfection 🤣

**Pull request merged**
